name: front_end_flutter_cortex_ia
description: "Frontend oficial do sistema CortexIA â€” Chamados com IA"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # ----------- PRINCIPAIS -------------
  http: ^1.2.0            
  provider: ^6.1.2        
  intl: ^0.19.0           
  mime: ^1.0.4
  http_parser: ^4.0.2
  diacritic: ^0.1.3
  shared_preferences: ^2.2.2

  # ----------- UI / IMAGENS / ASSETS -------
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10    
  image_picker: ^1.0.7  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
